<<<<<<< HEAD
env:
  global:
  - GH_OWNER: alefebvre
  - GH_PROJECT_NAME: Tool-box
  - secure: fuZ2ZUBVzKxSsau6KcezNecfszINrPGbz50aSb/NAPfO6SAZc8uKsGZGD2O0cJd7hkn8w0h/DbQu6zQt13Fp0dpmvL4BlZ73hP8IQTFGphHljvXTsoHodXzG4JpFqp43Uq/jSxV7aEsJ1fDjiDeG+3DgAKFopdYjZ28o9IbmmBY=
language: php
php:
- 5.3
- 5.4
- 5.5
before_script:
- curl -s http://getcomposer.org/installer | php
- php composer.phar install --prefer-source --no-interaction --dev
script: phpunit 
after_success:
- export POST_BUILD=true
- wget http://pear.phpunit.de/get/phploc.phar
- php phploc.phar src/ > build/result/phploc.txt
- wget https://github.com/downloads/apigen/apigen/ApiGen-2.8.0-standalone.zip --no-check-certificate
- unzip ApiGen-2.8.0-standalone.zip
- rm ApiGen-2.8.0-standalone.zip
- php apigen/apigen.php --source Application --destination build/result/docs/
- bash scrut.sh
- bash push_to_stable.sh
- bash push_to_gh_pages.sh
=======
language: php

php:
  - 5.4

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

script: phpunit --coverage-clover clover

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php

>>>>>>> fcfef520644b3d15fee53e8da42a64b6c95b14f1
